version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout
      # install dependencies
      - run: npm install
      # run tests!
      - run: npm run test
